---
TRADE_OPTIONS:
  # How often to check for posts and run the script in seconds
  FREQUENCY_SECONDS: 5
  TEST: True

  # Development debugging.  Leave False.
  BINANCE_TESTNET: False

  #  In theory, Binance/FTX will add a new coin at the start of a minute.
  # Enabling this option will have the program continuously query the APIs for 'FRONTLOAD_DURATION' seconds starting at
  # the 57th second of each minute.  A 'FRONTLOAD_DURATION' of 8 would query the API from 00:57 until 01:05.
  FRONTLOAD_REQUESTS:
    FRONTLOAD_ENABLED: True
    FRONTLOAD_DURATION: 8

  #  Brokers to run.  Make sure to set API keys in auth.yml
  BROKERS:
    BINANCE:
      ENABLED: True
      # quantify of QUOTE_TICKER (below) to be bought
      QUANTITY: 30
      # For example, BTCUSDT will be bought with pairing 'USDT'
      QUOTE_TICKER: 'USDT'
      # Most users will not have a Binance subaccount
      SUBACCOUNT: None
      # Auto-sell if price goes X% of original purchase price
      STOP_LOSS_PERCENT: 20
      # Auto-sell if price goes above Y% of original purchase price
      # TAKE_PROFIT_PERCENT is **IGNORED** if ENABLE_TRAILING_STOP_LOSS is True
      TAKE_PROFIT_PERCENT: 30
      # TAKE_PROFIT_PERCENT is **IGNORED** if ENABLE_TRAILING_STOP_LOSS is True
      ENABLE_TRAILING_STOP_LOSS: True
      #  Activate trailing stop loss once price is Z% above original purchase price
      TRAILING_STOP_LOSS_ACTIVATION: 35
      # Auto-sell if price goes X% below maximum price after activation
      TRAILING_STOP_LOSS_PERCENT: 10

    FTX:
      ENABLED: True
      QUANTITY: 30
      SUBACCOUNT: None
      QUOTE_TICKER: 'USDT'
      STOP_LOSS_PERCENT: 20
      TAKE_PROFIT_PERCENT: 30
      ENABLE_TRAILING_STOP_LOSS: True
      TRAILING_STOP_LOSS_ACTIVATION: 35
      TRAILING_STOP_LOSS_PERCENT: 10

PROGRAM_OPTIONS:
  # log level for output.  I recommend  either INFO or DEBUG
  LOG_LEVEL: DEBUG
  # how often, in minutes, to get a update message output
  LOG_INFO_UPDATE_INTERVAL: 2
  #  if true, any time a new LIVE order or sale occurs the resulting object will be sent to and logged to pipedream.com account.
  #  I'll use this info to build better test cases and it will help me catch edge cases and bugs.
  SHARE_DATA: True
NOTIFICATION_OPTIONS:
  DISCORD:
    ENABLED: True
    NAME: 'DISCORD'
    SETTINGS:
      SEND_MESSAGE: True
      SEND_ERROR: True
      SEND_WARNING: False
      SEND_INFO: False
      SEND_DEBUG: False
      SEND_ENTRY: True
      SEND_CLOSE: True
    AUTH:
      ENDPOINT: 'https://discord.com/api/webhooks/<...> -> Read readme for more info'
  TELEGRAM:
    ENABLED: True
    NAME: 'TELEGRAM'
    SETTINGS:
      SEND_MESSAGE: True
      SEND_ERROR: True
      SEND_WARNING: False
      SEND_INFO: False
      SEND_DEBUG: False
      SEND_ENTRY: True
      SEND_CLOSE: True
    AUTH:
      ENDPOINT: 'TOKEN -> Read readme for more info'
      CHAT_ID: 'XXXXXX -> Read readme for more info.  If this value is negative, keep the minus sign.'